#include <stdio.h>

int main(int argc, char **argv) {
  char buf[1000];

  printf("99 Bottles of Beer\n");
  printf("\n");
  printf("99 bottles of beer on the wall, \n");
  printf("99 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("98 bottles of beer on the wall. \n");
  printf("\n");
  printf("98 bottles of beer on the wall, \n");
  printf("98 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("97 bottles of beer on the wall. \n");
  printf("\n");
  printf("97 bottles of beer on the wall, \n");
  printf("97 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("96 bottles of beer on the wall. \n");
  printf("\n");
  printf("96 bottles of beer on the wall, \n");
  printf("96 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("95 bottles of beer on the wall. \n");
  printf("\n");
  printf("95 bottles of beer on the wall, \n");
  printf("95 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("94 bottles of beer on the wall. \n");
  printf("\n");
  printf("94 bottles of beer on the wall, \n");
  printf("94 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("93 bottles of beer on the wall. \n");
  printf("\n");
  printf("93 bottles of beer on the wall, \n");
  printf("93 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("92 bottles of beer on the wall. \n");
  printf("\n");
  printf("92 bottles of beer on the wall, \n");
  printf("92 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("91 bottles of beer on the wall. \n");
  printf("\n");
  printf("91 bottles of beer on the wall, \n");
  printf("91 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("90 bottles of beer on the wall. \n");
  printf("\n");
  printf("90 bottles of beer on the wall, \n");
  printf("90 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("89 bottles of beer on the wall. \n");
  printf("\n");
  printf("89 bottles of beer on the wall, \n");
  printf("89 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("88 bottles of beer on the wall. \n");
  printf("\n");
  printf("88 bottles of beer on the wall, \n");
  printf("88 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("87 bottles of beer on the wall. \n");
  printf("\n");
  printf("87 bottles of beer on the wall, \n");
  printf("87 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("86 bottles of beer on the wall. \n");
  printf("\n");
  printf("86 bottles of beer on the wall, \n");
  printf("86 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("85 bottles of beer on the wall. \n");
  printf("\n");
  printf("85 bottles of beer on the wall, \n");
  printf("85 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("84 bottles of beer on the wall. \n");
  printf("\n");
  printf("84 bottles of beer on the wall, \n");
  printf("84 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("83 bottles of beer on the wall. \n");
  printf("\n");
  printf("83 bottles of beer on the wall, \n");
  printf("83 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("82 bottles of beer on the wall. \n");
  printf("\n");
  printf("82 bottles of beer on the wall, \n");
  printf("82 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("81 bottles of beer on the wall. \n");
  printf("\n");
  printf("81 bottles of beer on the wall, \n");
  printf("81 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("80 bottles of beer on the wall. \n");
  printf("\n");
  printf("80 bottles of beer on the wall, \n");
  printf("80 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("79 bottles of beer on the wall. \n");
  printf("\n");
  printf("79 bottles of beer on the wall, \n");
  printf("79 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("78 bottles of beer on the wall. \n");
  printf("\n");
  printf("78 bottles of beer on the wall, \n");
  printf("78 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("77 bottles of beer on the wall. \n");
  printf("\n");
  printf("77 bottles of beer on the wall, \n");
  printf("77 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("76 bottles of beer on the wall. \n");
  printf("\n");
  printf("76 bottles of beer on the wall, \n");
  printf("76 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("75 bottles of beer on the wall. \n");
  printf("\n");
  printf("75 bottles of beer on the wall, \n");
  printf("75 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("74 bottles of beer on the wall. \n");
  printf("\n");
  printf("74 bottles of beer on the wall, \n");
  printf("74 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("73 bottles of beer on the wall. \n");
  printf("\n");
  printf("73 bottles of beer on the wall, \n");
  printf("73 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("72 bottles of beer on the wall. \n");
  printf("\n");
  printf("72 bottles of beer on the wall, \n");
  printf("72 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("71 bottles of beer on the wall. \n");
  printf("\n");
  printf("71 bottles of beer on the wall, \n");
  printf("71 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("70 bottles of beer on the wall. \n");
  printf("\n");
  printf("70 bottles of beer on the wall, \n");
  printf("70 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("69 bottles of beer on the wall. \n");
  printf("\n");
  printf("69 bottles of beer on the wall, \n");
  printf("69 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("68 bottles of beer on the wall. \n");
  printf("\n");
  printf("68 bottles of beer on the wall, \n");
  printf("68 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("67 bottles of beer on the wall. \n");
  printf("\n");
  printf("67 bottles of beer on the wall, \n");
  printf("67 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("66 bottles of beer on the wall. \n");
  printf("\n");
  printf("66 bottles of beer on the wall, \n");
  printf("66 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("65 bottles of beer on the wall. \n");
  printf("\n");
  printf("65 bottles of beer on the wall, \n");
  printf("65 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("64 bottles of beer on the wall. \n");
  printf("\n");
  printf("64 bottles of beer on the wall, \n");
  printf("64 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("63 bottles of beer on the wall. \n");
  printf("\n");
  printf("63 bottles of beer on the wall, \n");
  printf("63 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("62 bottles of beer on the wall. \n");
  printf("\n");
  printf("62 bottles of beer on the wall, \n");
  printf("62 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("61 bottles of beer on the wall. \n");
  printf("\n");
  printf("61 bottles of beer on the wall, \n");
  printf("61 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("60 bottles of beer on the wall. \n");
  printf("\n");
  printf("60 bottles of beer on the wall, \n");
  printf("60 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("59 bottles of beer on the wall. \n");
  printf("\n");
  printf("59 bottles of beer on the wall, \n");
  printf("59 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("58 bottles of beer on the wall. \n");
  printf("\n");
  printf("58 bottles of beer on the wall, \n");
  printf("58 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("57 bottles of beer on the wall. \n");
  printf("\n");
  printf("57 bottles of beer on the wall, \n");
  printf("57 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("56 bottles of beer on the wall. \n");
  printf("\n");
  printf("56 bottles of beer on the wall, \n");
  printf("56 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("55 bottles of beer on the wall. \n");
  printf("\n");
  printf("55 bottles of beer on the wall, \n");
  printf("55 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("54 bottles of beer on the wall. \n");
  printf("\n");
  printf("54 bottles of beer on the wall, \n");
  printf("54 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("53 bottles of beer on the wall. \n");
  printf("\n");
  printf("53 bottles of beer on the wall, \n");
  printf("53 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("52 bottles of beer on the wall. \n");
  printf("\n");
  printf("52 bottles of beer on the wall, \n");
  printf("52 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("51 bottles of beer on the wall. \n");
  printf("\n");
  printf("51 bottles of beer on the wall, \n");
  printf("51 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("50 bottles of beer on the wall. \n");
  printf("\n");
  printf("50 bottles of beer on the wall, \n");
  printf("50 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("49 bottles of beer on the wall. \n");
  printf("\n");
  printf("49 bottles of beer on the wall, \n");
  printf("49 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("48 bottles of beer on the wall. \n");
  printf("\n");
  printf("48 bottles of beer on the wall, \n");
  printf("48 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("47 bottles of beer on the wall. \n");
  printf("\n");
  printf("47 bottles of beer on the wall, \n");
  printf("47 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("46 bottles of beer on the wall. \n");
  printf("\n");
  printf("46 bottles of beer on the wall, \n");
  printf("46 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("45 bottles of beer on the wall. \n");
  printf("\n");
  printf("45 bottles of beer on the wall, \n");
  printf("45 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("44 bottles of beer on the wall. \n");
  printf("\n");
  printf("44 bottles of beer on the wall, \n");
  printf("44 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("43 bottles of beer on the wall. \n");
  printf("\n");
  printf("43 bottles of beer on the wall, \n");
  printf("43 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("42 bottles of beer on the wall. \n");
  printf("\n");
  printf("42 bottles of beer on the wall, \n");
  printf("42 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("41 bottles of beer on the wall. \n");
  printf("\n");
  printf("41 bottles of beer on the wall, \n");
  printf("41 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("40 bottles of beer on the wall. \n");
  printf("\n");
  printf("40 bottles of beer on the wall, \n");
  printf("40 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("39 bottles of beer on the wall. \n");
  printf("\n");
  printf("39 bottles of beer on the wall, \n");
  printf("39 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("38 bottles of beer on the wall. \n");
  printf("\n");
  printf("38 bottles of beer on the wall, \n");
  printf("38 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("37 bottles of beer on the wall. \n");
  printf("\n");
  printf("37 bottles of beer on the wall, \n");
  printf("37 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("36 bottles of beer on the wall. \n");
  printf("\n");
  printf("36 bottles of beer on the wall, \n");
  printf("36 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("35 bottles of beer on the wall. \n");
  printf("\n");
  printf("35 bottles of beer on the wall, \n");
  printf("35 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("34 bottles of beer on the wall. \n");
  printf("\n");
  printf("34 bottles of beer on the wall, \n");
  printf("34 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("33 bottles of beer on the wall. \n");
  printf("\n");
  printf("33 bottles of beer on the wall, \n");
  printf("33 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("32 bottles of beer on the wall. \n");
  printf("\n");
  printf("32 bottles of beer on the wall, \n");
  printf("32 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("31 bottles of beer on the wall. \n");
  printf("\n");
  printf("31 bottles of beer on the wall, \n");
  printf("31 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("30 bottles of beer on the wall. \n");
  printf("\n");
  printf("30 bottles of beer on the wall, \n");
  printf("30 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("29 bottles of beer on the wall. \n");
  printf("\n");
  printf("29 bottles of beer on the wall, \n");
  printf("29 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("28 bottles of beer on the wall. \n");
  printf("\n");
  printf("28 bottles of beer on the wall, \n");
  printf("28 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("27 bottles of beer on the wall. \n");
  printf("\n");
  printf("27 bottles of beer on the wall, \n");
  printf("27 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("26 bottles of beer on the wall. \n");
  printf("\n");
  printf("26 bottles of beer on the wall, \n");
  printf("26 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("25 bottles of beer on the wall. \n");
  printf("\n");
  printf("25 bottles of beer on the wall, \n");
  printf("25 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("24 bottles of beer on the wall. \n");
  printf("\n");
  printf("24 bottles of beer on the wall, \n");
  printf("24 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("23 bottles of beer on the wall. \n");
  printf("\n");
  printf("23 bottles of beer on the wall, \n");
  printf("23 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("22 bottles of beer on the wall. \n");
  printf("\n");
  printf("22 bottles of beer on the wall, \n");
  printf("22 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("21 bottles of beer on the wall. \n");
  printf("\n");
  printf("21 bottles of beer on the wall, \n");
  printf("21 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("20 bottles of beer on the wall. \n");
  printf("\n");
  printf("20 bottles of beer on the wall, \n");
  printf("20 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("19 bottles of beer on the wall. \n");
  printf("\n");
  printf("19 bottles of beer on the wall, \n");
  printf("19 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("18 bottles of beer on the wall. \n");
  printf("\n");
  printf("18 bottles of beer on the wall, \n");
  printf("18 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("17 bottles of beer on the wall. \n");
  printf("\n");
  printf("17 bottles of beer on the wall, \n");
  printf("17 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("16 bottles of beer on the wall. \n");
  printf("\n");
  printf("16 bottles of beer on the wall, \n");
  printf("16 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("15 bottles of beer on the wall. \n");
  printf("\n");
  printf("15 bottles of beer on the wall, \n");
  printf("15 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("14 bottles of beer on the wall. \n");
  printf("\n");
  printf("14 bottles of beer on the wall, \n");
  printf("14 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("13 bottles of beer on the wall. \n");
  printf("\n");
  printf("13 bottles of beer on the wall, \n");
  printf("13 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("12 bottles of beer on the wall. \n");
  printf("\n");
  printf("12 bottles of beer on the wall, \n");
  printf("12 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("11 bottles of beer on the wall. \n");
  printf("\n");
  printf("11 bottles of beer on the wall, \n");
  printf("11 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("10 bottles of beer on the wall. \n");
  printf("\n");
  printf("10 bottles of beer on the wall, \n");
  printf("10 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("9 bottles of beer on the wall. \n");
  printf("\n");
  printf("9 bottles of beer on the wall, \n");
  printf("9 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("8 bottles of beer on the wall. \n");
  printf("\n");
  printf("8 bottles of beer on the wall, \n");
  printf("8 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("7 bottles of beer on the wall. \n");
  printf("\n");
  printf("7 bottles of beer on the wall, \n");
  printf("7 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("6 bottles of beer on the wall. \n");
  printf("\n");
  printf("6 bottles of beer on the wall, \n");
  printf("6 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("5 bottles of beer on the wall. \n");
  printf("\n");
  printf("5 bottles of beer on the wall, \n");
  printf("5 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("4 bottles of beer on the wall. \n");
  printf("\n");
  printf("4 bottles of beer on the wall, \n");
  printf("4 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("3 bottles of beer on the wall. \n");
  printf("\n");
  printf("3 bottles of beer on the wall, \n");
  printf("3 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("2 bottles of beer on the wall. \n");
  printf("\n");
  printf("2 bottles of beer on the wall, \n");
  printf("2 bottles of beer. \n");
  printf("Take one down, pass it around, \n");
  printf("1 bottle of beer on the wall. \n");
  printf("\n");
  printf("1 bottle of beer on the wall, \n");
  printf("1 bottle of beer. \n");
  printf("Take it down, pass it around, \n");
  printf("No bottles of beer on the wall, \n");
  printf("No bottles of beer.\n");
  printf("\n");
  printf("Do you want to UNDO, RESTART, RESTORE or QUIT ? \n");

  fgets(buf, 1000, stdin);
  printf(buf);
}
